DROP DATABASE IF EXISTS DataType;
CREATE DATABASE DataType;
USE DataType;
CREATE TABLE `Data`(
ID		 		MEDIUMINT UNIQUE PRIMARY KEY AUTO_INCREMENT,
`Name` 			VARCHAR(30),
`Code`			CHAR(5) UNIQUE,
ModifiedDate	DATETIME
);
